### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by BunnySK** [Laokuai233/Twilight-Delight#2]
Hello, I hope you are doing well just wanted to give you some feedback on your mod. Firstly, please make it easier to find your issue tracker and a proper way to provide feedback on your Modrinth page. Secondly, in the most recent version, your mod bugs the knife and bowls from being able to properly interact with pies and things like stuffed pumpkins. I troubleshot this to see if any other mods were causing it but I found that it was your mod was the culprit of this. Thirdly, I like the work you've done, but I feel like it isn't capturing the novelty of Farmer's Delight. Lots of your food is ridiculously broken with a high saturation count so I would like to give you a suggestion. In Farmer's delight many foods can be cut with a knife or broken down with a bowl, could you transform these into their own blocks like the stuffed pumpkins I think that fits the spirit of Farmer's Delight much more. If you read this, thank you for hearing me out and I appreciate your hard work.

**Comment by Laokuai233** [comment]
Try the latest version.It fixed the bug about knives.

**Comment by Laokuai233** [comment]
Try the latest version 1.1.1.It fixed the bug about knives.

**Comment by BunnySK** [comment]
Thank you, as for 1.1.3 I thought it was a weird choice to make the Lily Chicken 3D yet not meant to be taken apart by a bowl. But regardless I did enjoy the changes you made.

Also just a small thing in the lang folder "twilightdelight.feast.error": "It cannot easily be parted. Try to part it by the crafting table!", 

+ add space

**Comment by ZephyrWindSpirit** [comment]
> Try the latest version 1.1.1.It fixed the bug about knives.

I've discovered an issue with the knives and twilight delight again, with 1.1.4+ of twilight delight. 
All knives don't right click harvest rice properly anymore, just harvesting straw, no rice.
